#  ╔═╗╦  ╔═╗╔═╗╦═╗╦╔╦╗╔╦╗╦ ╦  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠═╣║  ╠═╣║  ╠╦╝║ ║  ║ ╚╦╝  ║  ║ ║║║║╠╣ ║║ ╦	- Config by z0mbi3
#  ╩ ╩╩═╝╩ ╩╚═╝╩╚═╩ ╩  ╩  ╩   ╚═╝╚═╝╝╚╝╚  ╩╚═╝	- https://github.com/gh0stzk/dotfiles
#  General configuration
  
window:
  padding:
    x: 15
    y: 15

  decorations: none

  opacity: 1.0
  dynamic_title: true

  history: 10000
  multiplier: 3

selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: On
    
  unfocused_hollow: false 
  blink_interval: 550

live_config_reload: true

colors:
    primary:
        background: "#1E1E2E" # base
        foreground: "#CDD6F4" # text
        # Bright and dim foreground colors
        dim_foreground: "#CDD6F4" # text
        bright_foreground: "#CDD6F4" # text

    # Cursor colors
    cursor:
        text: "#1E1E2E" # base
        cursor: "#F5E0DC" # rosewater
    vi_mode_cursor:
        text: "#1E1E2E" # base
        cursor: "#B4BEFE" # lavender

    # Search colors
    search:
        matches:
            foreground: "#1E1E2E" # base
            background: "#A6ADC8" # subtext0
        focused_match:
            foreground: "#1E1E2E" # base
            background: "#A6E3A1" # green
        footer_bar:
            foreground: "#1E1E2E" # base
            background: "#A6ADC8" # subtext0

    # Keyboard regex hints
    hints:
        start:
            foreground: "#1E1E2E" # base
            background: "#F9E2AF" # yellow
        end:
            foreground: "#1E1E2E" # base
            background: "#A6ADC8" # subtext0

    # Selection colors
    selection:
        text: "#1E1E2E" # base
        background: "#F5E0DC" # rosewater

    # Normal colors
    normal:
        black: "#000000" # surface1
        red: "#FABCC3" # red
        green: "#FABCC3" # green
        yellow: "#FABCC3" # yellow
        blue: "#FABCC3" # blue
        magenta: "#FABCC3" # pink
        cyan: "#FABCC3" # teal
        white: "#FABCC3" # subtext1

    # Bright colors
    bright:
        black: "#FABCC3" # surface1
        red: "#FABCC3" # red
        green: "#FABCC3" # green
        yellow: "#FABCC3" # yellow
        blue: "#FABCC3" # blue
        magenta: "#FABCC3" # pink
        cyan: "#FABCC3" # teal
        white: "#FABCC3" # subtext1

    # Dim colors
    dim:
        black: "#000000" # surface1
        red: "#FABCC3" # red
        green: "#FABCC3" # green
        yellow: "#FABCC3" # yellow
        blue: "#FABCC3" # blue
        magenta: "#FABCC3" # pink
        cyan: "#FABCC3" # teal
        white: "#FABCC3" # subtext1

    indexed_colors:
        - { index: 16, color: "#FAB387" }
        - { index: 17, color: "#F5E0DC" }
        
#  Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font
    #style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    #style: Bold
  
  italic:
    family: JetBrainsMono Nerd Font
    #style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    #style: Bold Italic

  size: 10
